server:
  port: 9090
spring:
  datasource:
    #url: jdbc:mysql://localhost:3307/cardsdb
    #username: root
    #password: root

    url: jdbc:h2:mem:cardsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

  jpa:
    show-sql: true
  sql:
    init:
      mode: always
