server:
  port: 8090
spring:
  datasource:
    #url: jdbc:mysql://localhost:3308/loansdb
    #username: root
    #password: root

    url: jdbc:h2:mem:loansdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
  jpa:
    show-sql: true
  sql:
    init:
      mode: always