
server:
  port: 8080
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/accountsdb
    #username: root
    #password: root

    url: jdbc:h2:mem:accountsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

  jpa:
    show-sql: true
  sql:
    init:
      mode: always