spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        search-locations: "classpath:/config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enable: true
    liveness-state:
      enable: true
    endpoint:
      health:
        probes:
          enable: true

server:
  port: 8071

